name: stegano
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.1+1
  entry: ^0.0.8+1

  flutter_svg: ^2.0.2
  shared_preferences: ^2.0.18
  http: ^0.13.5
  dio: ^5.0.1
  cached_network_image: ^3.2.3
  lottie: ^2.3.2
  image_picker: ^1.0.0
  path_provider: ^2.0.15
  fluttertoast: ^8.2.2
#  flutter_native_splash: ^2.2.19

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
  fonts:
      - family: BasierCircle
        fonts:
          - asset: assets/fonts/BasierCircle-Bold.ttf
          - asset: assets/fonts/BasierCircle-Medium.ttf
          - asset: assets/fonts/BasierCircle-Regular.ttf

